# Generated by Django 4.1.13 on 2025-09-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_item_alter_userprofile_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
