# Generated by Django 4.1.13 on 2025-10-14 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.category'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='Quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
