# Generated by Django 4.1.13 on 2025-09-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, default='profile_pic/image.png', null=True, upload_to='user_path/'),
        ),
    ]
