# Generated by Django 4.1.13 on 2025-10-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_category_name_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_pending_admin',
            field=models.BooleanField(default=False),
        ),
    ]
