# Generated by Django 4.1.13 on 2025-09-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='profile_pic/image.png', upload_to='user_path/'),
        ),
    ]
