# Generated by Django 4.1.13 on 2025-09-29 11:30

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='profilepic/image.png', upload_to=user.models.image_path),
        ),
    ]
