# Generated by Django 4.1.13 on 2025-10-07 12:39

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_inventoryitem_alter_userprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, default='profilepic/default.png', null=True, upload_to=user.models.image_path),
        ),
    ]
